// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "vlrggapi Maintainers",
            "url": "https://github.com/yourusername/vlrggapi"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/vlr/events": {
            "get": {
                "description": "Returns a list of upcoming or completed Valorant events",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get Valorant events",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "If true, return only upcoming events",
                        "name": "upcoming",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "If true, return only completed events",
                        "name": "completed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vlr/health": {
            "get": {
                "description": "Returns health status of the API and upstream sources",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/vlr/live": {
            "get": {
                "description": "Returns live match scores from VLR.GG",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Get live Valorant match scores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vlr/match": {
            "get": {
                "description": "Returns upcoming scheduled matches or recent match results, depending on query params.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Get Valorant match schedule or results",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "If true, return upcoming/scheduled matches (default: false)",
                        "name": "schedule",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "If true, return match results (default: true)",
                        "name": "results",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Number of pages to fetch (results only)",
                        "name": "num_pages",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Start page (results only)",
                        "name": "from_page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "End page (results only)",
                        "name": "to_page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 3,
                        "description": "Retry attempts per page (results only)",
                        "name": "max_retries",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "default": 1,
                        "description": "Delay between requests (seconds, results only)",
                        "name": "request_delay",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "HTTP timeout (seconds, results only)",
                        "name": "timeout",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vlr/news": {
            "get": {
                "description": "Returns a list of recent Valorant news articles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Get latest Valorant news",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vlr/rankings": {
            "get": {
                "description": "Returns team rankings for a given region",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rankings"
                ],
                "summary": "Get Valorant team rankings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Region key (e.g. na, eu, ap, la, oce, kr, mn, gc, br, cn, jp, col)",
                        "name": "region",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vlr/stats": {
            "get": {
                "description": "Returns player statistics, filterable by region and timespan",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get Valorant player statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Region key (e.g. na, eu, ap, la, oce, kr, mn, gc, br, cn, jp, col)",
                        "name": "region",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Timespan (e.g. all, 30 for 30 days)",
                        "name": "timespan",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "vlrggapi",
	Description:      "REST API for scraping Valorant esports data from vlr.gg",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
